apiVersion: v2
appVersion: 0.6.1
description: Highly scalable and standards based Model Inference Platform on Kubernetes
home: https://kserve.github.io/website/
icon: https://raw.githubusercontent.com/kserve/artwork/main/icon/color/k-serve-icon-color.svg
maintainers:
  - name: sebastien-prudhomme
    email: sebastien.prudhomme@gmail.com
name: kfserving
sources:
  - https://github.com/kserve/kserve
  - https://github.com/cowboysysop/charts/tree/master/charts/kfserving
version: 1.4.0
dependencies:
  - name: common
    version: 1.17.1
    repository: https://charts.bitnami.com/bitnami/
annotations:
  artifacthub.io/signKey: |
    fingerprint: 9E57D2479D48B84463EF491F66D280CE667AD6C8
    url: https://cowboysysop.github.io/charts/pgp-public-key-2022-02-19.asc
  kubeVersion: ">=1.19 <=1.21"
